name: Update ONS Torridge population

on:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch ONS data
        run: node scripts/fetch.mjs

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/data.json
          git diff --quiet && echo "No changes." || git commit -m "chore: update ONS data"
          git push
